<div class="col-md-6">
	<h2 class="sub-header">Ventas premium</h2>
	<div class="table-responsive">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Usuario</th>
					<th>Monto</th>
					<th>Fecha</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Lorem</td>
					<td>ipsum</td>
					<td>dolor</td>
				</tr>
				<tr>
					<td>amet</td>
					<td>consectetur</td>
					<td>adipiscing</td>
				</tr>
				<tr>
					<td>Integer</td>
					<td>nec</td>
					<td>odio</td>
				</tr>
				<tr>
					<td>libero</td>
					<td>Sed</td>
					<td>cursus</td>
				</tr>
				<tr>
					<td>dapibus</td>
					<td>diam</td>
					<td>Sed</td>
				</tr>
				<tr>
					<td>Nulla</td>
					<td>quis</td>
					<td>sem</td>
				</tr>
				<tr>
					<td>nibh</td>
					<td>elementum</td>
					<td>imperdiet</td>
				</tr>
				<tr>
					<td>sagittis</td>
					<td>ipsum</td>
					<td>Praesent</td>
				</tr>
				<tr>
					<td>Fusce</td>
					<td>nec</td>
					<td>tellus</td>
				</tr>
				<tr>
					<td>augue</td>
					<td>semper</td>
					<td>porta</td>
				</tr>
				<tr>
					<td>massa</td>
					<td>Vestibulum</td>
					<td>lacinia</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div class="col-md-6">
	<h2 class="sub-header">Reservas Concretadas</h2>
	<div class="table-responsive">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Usuario</th>
					<th>Couch</th>
					<th>Fecha</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Lorem</td>
					<td>ipsum</td>
					<td>dolor</td>
				</tr>
				<tr>
					<td>amet</td>
					<td>consectetur</td>
					<td>adipiscing</td>
				</tr>
				<tr>
					<td>Integer</td>
					<td>nec</td>
					<td>odio</td>
				</tr>
				<tr>
					<td>libero</td>
					<td>Sed</td>
					<td>cursus</td>
				</tr>
				<tr>
					<td>dapibus</td>
					<td>diam</td>
					<td>Sed</td>
				</tr>
				<tr>
					<td>Nulla</td>
					<td>quis</td>
					<td>sem</td>
				</tr>
				<tr>
					<td>nibh</td>
					<td>elementum</td>
					<td>imperdiet</td>
				</tr>
				<tr>
					<td>sagittis</td>
					<td>ipsum</td>
					<td>Praesent</td>
				</tr>
				<tr>
					<td>Fusce</td>
					<td>nec</td>
					<td>tellus</td>
				</tr>
				<tr>
					<td>augue</td>
					<td>semper</td>
					<td>porta</td>
				</tr>
				<tr>
					<td>massa</td>
					<td>Vestibulum</td>
					<td>lacinia</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>